package Model;
// Generated 28/11/2019 10:22:53 AM by Hibernate Tools 4.3.1



/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


    private int idAlumn;
    private String nombAlumn;

    public Alumno() {
    }

	
    public Alumno(int idAlumn) {
        this.idAlumn = idAlumn;
    }
    public Alumno(int idAlumn, String nombAlumn) {
       this.idAlumn = idAlumn;
       this.nombAlumn = nombAlumn;
    }
   
    public int getIdAlumn() {
        return this.idAlumn;
    }
    
    public void setIdAlumn(int idAlumn) {
        this.idAlumn = idAlumn;
    }
    public String getNombAlumn() {
        return this.nombAlumn;
    }
    
    public void setNombAlumn(String nombAlumn) {
        this.nombAlumn = nombAlumn;
    }




}


